# Generated by Django 5.1.5 on 2025-03-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='desciption',
            new_name='description',
        ),
    ]
